import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export type VehicleDocument = Vehicle & Document;

export enum VehicleStatus {
  NEW = 'new',
  INSPECTION = 'inspection',
  UNSOLD = 'unsold',
  TEST_DRIVE = 'test_drive',
  RESERVED = 'reserved',
  PENDING = 'pending',
  SOLD = 'sold',
}

export enum HostingType {
  SELF = 'self',
  PLATFORM = 'platform',
}

export enum FuelType {
  PETROL = 'petrol',
  DIESEL = 'diesel',
  ELECTRIC = 'electric',
  HYBRID = 'hybrid',
  CNG = 'cng',
}

export enum Transmission {
  MANUAL = 'manual',
  AUTOMATIC = 'automatic',
  CVT = 'cvt',
}

@Schema({ timestamps: true })
class TrafficLog {
  @Prop({ default: 0 }) views: number;
  @Prop({ default: 0 }) clicks: number;
  @Prop({ default: 0 }) inquiries: number;
  @Prop({ type: Date }) lastViewed: Date;
}

@Schema({ timestamps: true, collection: 'vehicles' })
export class Vehicle {
  /**
   * Human-readable identifier (e.g. "V-A8F2X"). Auto-generated by the service
   * if not provided. Unique across the dealership.
   */
  @ApiProperty() @Prop({ required: true, unique: true, uppercase: true, trim: true }) vehicleNumber: string;
  @ApiProperty() @Prop({ required: true, trim: true }) title: string;
  @ApiProperty() @Prop({ default: '' }) description: string;
  @ApiProperty() @Prop({ type: [String], default: [] }) photos: string[];
  @ApiProperty() @Prop({ required: true }) company: string;
  @ApiProperty() @Prop({ required: true }) model: string;
  @ApiProperty() @Prop({ required: true, min: 1900, max: 2100 }) year: number;
  @ApiProperty() @Prop({ default: 0, min: 0 }) km: number;
  @ApiProperty() @Prop({ required: true, min: 0 }) price: number;
  /** Absolute discount in the dealership's currency (dollars). Not a percentage. */
  @ApiProperty() @Prop({ default: 0, min: 0 }) discount: number;
  /** What the dealership paid to acquire the car. Drives gross-margin maths. */
  @ApiPropertyOptional() @Prop({ default: 0, min: 0 }) costPrice: number;
  /** Realised sale price (set when the vehicle is sold — usually salePrice−discount). */
  @ApiPropertyOptional() @Prop({ default: 0, min: 0 }) soldAt: number;
  @ApiPropertyOptional() @Prop({ type: Date, default: null }) soldDate: Date | null;
  @ApiProperty() @Prop({ default: 1, min: 1 }) owners: number;
  @ApiProperty({ enum: FuelType }) @Prop({ type: String, enum: FuelType }) fuelType: FuelType;
  @ApiProperty({ enum: Transmission }) @Prop({ type: String, enum: Transmission }) transmission: Transmission;
  @ApiProperty() @Prop({ default: '' }) color: string;
  @ApiProperty() @Prop({ default: '' }) vin: string;
  /** Free-text body type from VIN decoder (e.g. "Sedan", "Pickup Truck", "SUV"). */
  @ApiProperty() @Prop({ default: '' }) bodyType: string;
  @ApiProperty({ enum: VehicleStatus }) @Prop({ type: String, enum: VehicleStatus, default: VehicleStatus.PENDING }) status: VehicleStatus;
  @ApiProperty({ enum: HostingType }) @Prop({ type: String, enum: HostingType, default: HostingType.PLATFORM }) hosting: HostingType;
  @ApiProperty() @Prop({ type: [String], default: [] }) features: string[];
  @ApiProperty() @Prop({ type: [{ field: String, value: String, changedAt: Date, changedBy: String }], default: [] }) history: any[];
  @ApiProperty() @Prop({ type: TrafficLog, default: {} }) traffic: TrafficLog;
  @ApiProperty() @Prop({ type: Types.ObjectId, ref: 'User' }) addedBy: Types.ObjectId;
  /**
   * Optional link to the SellerLead this vehicle was acquired from.
   * `null` means in-house ("Self") — the dealership added the car directly.
   */
  @ApiPropertyOptional() @Prop({ type: Types.ObjectId, ref: 'SellerLead', default: null }) seller: Types.ObjectId | null;
  @ApiProperty() @Prop({ default: false }) isDeleted: boolean;
  @Prop() deletedAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export const VehicleSchema = SchemaFactory.createForClass(Vehicle);

// Note: vehicleNumber gets a unique index via @Prop({ unique: true }) above; no explicit index here.
VehicleSchema.index({ status: 1, company: 1, model: 1 });
VehicleSchema.index({ price: 1 });
VehicleSchema.index({ '$**': 'text' }, { name: 'vehicle_text_index' });
