import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export type VehicleDocument = Vehicle & Document;

export enum VehicleStatus {
  /** Freshly added stock. Auto-expires to NONE after 2 days (see cron). */
  NEW = 'new',
  /** Sold. Stamps soldAt/soldDate; shown with a SOLD badge/ribbon. */
  SOLD = 'sold',
  /**
   * No status — the car is simply available for sale (no badge). Cars leave
   * NEW for this after 2 days, and un-selling a car returns it here. Stored as
   * an empty string so "available" is the natural default state.
   */
  NONE = '',
}

export enum HostingType {
  SELF = 'self',
  PLATFORM = 'platform',
}

export enum FuelType {
  PETROL = 'petrol',
  DIESEL = 'diesel',
  ELECTRIC = 'electric',
  HYBRID = 'hybrid',
  CNG = 'cng',
}

export enum Transmission {
  MANUAL = 'manual',
  AUTOMATIC = 'automatic',
  CVT = 'cvt',
}

@Schema({ timestamps: true })
class TrafficLog {
  @Prop({ default: 0 }) views: number;
  @Prop({ default: 0 }) clicks: number;
  @Prop({ default: 0 }) inquiries: number;
  @Prop({ type: Date }) lastViewed: Date;
}

@Schema({ timestamps: true, collection: 'vehicles' })
export class Vehicle {
  /**
   * Human-readable identifier (e.g. "V-A8F2X"). Auto-generated by the service
   * if not provided. Unique across the dealership.
   */
  @ApiProperty() @Prop({ required: true, unique: true, uppercase: true, trim: true }) vehicleNumber: string;
  @ApiProperty() @Prop({ required: true, trim: true }) title: string;
  @ApiProperty() @Prop({ default: '' }) description: string;
  @ApiProperty() @Prop({ type: [String], default: [] }) photos: string[];
  @ApiProperty() @Prop({ required: true }) company: string;
  @ApiProperty() @Prop({ required: true }) model: string;
  @ApiProperty() @Prop({ required: true, min: 1900, max: 2100 }) year: number;
  @ApiProperty() @Prop({ default: 0, min: 0 }) km: number;
  @ApiProperty() @Prop({ required: true, min: 0 }) price: number;
  /** Absolute discount in the dealership's currency (dollars). Not a percentage. */
  @ApiProperty() @Prop({ default: 0, min: 0 }) discount: number;
  /** What the dealership paid to acquire the car. Drives gross-margin maths. */
  @ApiPropertyOptional() @Prop({ default: 0, min: 0 }) costPrice: number;
  /** Realised sale price (set when the vehicle is sold — usually salePrice−discount). */
  @ApiPropertyOptional() @Prop({ default: 0, min: 0 }) soldAt: number;
  @ApiPropertyOptional() @Prop({ type: Date, default: null }) soldDate: Date | null;
  @ApiProperty() @Prop({ default: 1, min: 1 }) owners: number;
  @ApiProperty({ enum: FuelType }) @Prop({ type: String, enum: FuelType }) fuelType: FuelType;
  @ApiProperty({ enum: Transmission }) @Prop({ type: String, enum: Transmission }) transmission: Transmission;
  @ApiProperty() @Prop({ default: '' }) color: string;
  @ApiProperty() @Prop({ default: '' }) vin: string;
  /** Free-text body type from VIN decoder (e.g. "Sedan", "Pickup Truck", "SUV"). */
  @ApiProperty() @Prop({ default: '' }) bodyType: string;
  /** Trim / series (e.g. "XSE", "Sport"). Free-text; VIN decoder fills it. */
  @ApiPropertyOptional() @Prop({ default: '' }) trim: string;
  /** Engine summary (e.g. "2.0L · 4-cyl · 200hp"). Free-text; VIN decoder fills it. */
  @ApiPropertyOptional() @Prop({ default: '' }) engine: string;
  /** Drive configuration (e.g. "FWD", "AWD", "4X4", "RWD"). */
  @ApiPropertyOptional() @Prop({ default: '' }) drivetrain: string;
  /** Engine displacement (e.g. "3.6 L"); `engine` holds the fuller summary. */
  @ApiPropertyOptional() @Prop({ default: '' }) engineSize: string;
  /** Interior colour (exterior colour is `color`). */
  @ApiPropertyOptional() @Prop({ default: '' }) interiorColor: string;
  /** Number of doors. */
  @ApiPropertyOptional() @Prop({ default: 0, min: 0 }) doors: number;
  /**
   * Lifecycle status — only NEW, SOLD, or NONE(''). Defaults to NEW for freshly
   * added vehicles; the `InventoryService.expireNewVehicles` cron flips any
   * vehicle still in NEW after 2 days of createdAt over to NONE (no status /
   * available). A recorded sale sets SOLD; un-selling returns it to NONE.
   */
  @ApiProperty({ enum: VehicleStatus }) @Prop({ type: String, enum: VehicleStatus, default: VehicleStatus.NEW }) status: VehicleStatus;
  @ApiProperty({ enum: HostingType }) @Prop({ type: String, enum: HostingType, default: HostingType.PLATFORM }) hosting: HostingType;
  /**
   * Deliberate "show on the public dealer website" flag — independent of sale
   * status. The public `/website/inventory` endpoint returns only vehicles with
   * this true AND status ∈ {unsold, sold}; a published sold car renders with a
   * "Sold" badge, a published unsold car is available, and anything unpublished
   * never appears. Defaults to true so newly-added stock is listed once it goes
   * unsold; the dealer toggles it on the Dealer Website page.
   */
  @ApiProperty() @Prop({ default: true }) publishedToWebsite: boolean;
  @ApiProperty() @Prop({ type: [String], default: [] }) features: string[];
  @ApiProperty() @Prop({ type: [{ field: String, value: String, changedAt: Date, changedBy: String }], default: [] }) history: any[];
  /**
   * Money spent reconditioning the car BEFORE it sells (repairs, service,
   * parts, transport, detailing, …). These are cost-of-goods, not operating
   * expenses: the sum is snapshotted onto the Sale (`Sale.totalSpend`) at sale
   * time and folded into the gross-margin maths (profit = revenue − costPrice
   * − totalSpend). Adding is blocked once the vehicle is sold; deleting an
   * existing entry re-syncs the Sale snapshot. `by` is a captured name
   * snapshot (mirrors Lead.timeline.by) so no populate is needed.
   */
  @ApiProperty() @Prop({
    type: [{
      amount: { type: Number, required: true, min: 0 },
      category: { type: String, default: 'other' },
      description: { type: String, default: '' },
      date: { type: Date, default: Date.now },
      by: { type: String, default: '' },
    }],
    default: [],
  }) spends: { amount: number; category: string; description: string; date: Date; by: string }[];
  @ApiProperty() @Prop({ type: TrafficLog, default: {} }) traffic: TrafficLog;
  @ApiProperty() @Prop({ type: Types.ObjectId, ref: 'User' }) addedBy: Types.ObjectId;
  /**
   * Optional link to the SellerLead this vehicle was acquired from.
   * `null` means in-house ("Self") — the dealership added the car directly.
   */
  @ApiPropertyOptional() @Prop({ type: Types.ObjectId, ref: 'SellerLead', default: null }) seller: Types.ObjectId | null;
  @ApiProperty() @Prop({ default: false }) isDeleted: boolean;
  @Prop() deletedAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export const VehicleSchema = SchemaFactory.createForClass(Vehicle);

// Note: vehicleNumber gets a unique index via @Prop({ unique: true }) above; no explicit index here.
VehicleSchema.index({ status: 1, company: 1, model: 1 });
VehicleSchema.index({ price: 1 });
VehicleSchema.index({ '$**': 'text' }, { name: 'vehicle_text_index' });
